### ISSUE TITLE
hosts-file.net/ad_servers.txt Not found

### ISSUE THREAD

**Issue by headshotklaus** [deividgdt/ytadsblocker#1]
Just installed YTAdsblock on my Rasperry. Unfortunately it says during the installation:

Target: hosts-file.net (ad_servers.txt)
Status: Not found
List download failed: No cached list available

in my Pi hole Blocklist Section it shows the ad_servers.txt but if i click on that its unavailable too (Not found)

is there a fix or a workaround available? Thanks in advance

**Comment by deividgdt** [comment]
Hi,

This is not an error of the script, it is an error of Pi-hole. 

With a default installation of Pi-hole it comes some Blacklist, one of them is: https://hosts-file.net/ad_servers.txt, this list is not working anymore. 

If you do not want to see that error, just delete the list from Blacklist Section.
