### ISSUE TITLE
ytadsblocker.sh service error on centos 

### ISSUE THREAD

**Issue by langkhach270389** [deividgdt/ytadsblocker#10]
Hi Dev

First thank you for your amazing project.  I have tried and working fine on cenos7 with pihole v5.3.1 installed.  But only for script ytadsblocker_legacy.sh, also for script ytadsblocker.sh service error.  If you have time, you can check it out a bit.  And I also see some problems with youtube ads.  You can consider fixing that problem by changing blocking mode on pihole http https ssl response statuscode 200, which in my opinion would be better.  Skipping ads will be faster, avoiding the error of being stuck where ads can appear.  Finally thank you very much

**Comment by deividgdt** [comment]
Hi @langkhach270389 ,

The script ytadsblocker_legacy.sh it's for previous versions of Pihole 5.0, so using the legacy file with the version 5.4.1 won't work at all.

Could you provide me more information regarding that "service error"? Anyway I'll test it on CentOS 7.

Kind regards

**Comment by langkhach270389** [comment]
I can confirm that legacy.sh script still works great on pihole 5.3.1 if I combine with proxy server + Pi-hole + change blocking mode to ip-nodata-aaaa.  must open port 443 ( ads return https://0.0.0 response status code:200). Using proxy anywhere

**Comment by langkhach270389** [comment]
![Uploading F0CCAF99-5B5E-4268-9564-CF3C608E6FA8.png…]()

**Comment by langkhach270389** [comment]
![7BC40222-1526-40EB-9F3E-96DBEE037185](https://user-images.githubusercontent.com/13623692/130551344-2cd0f342-9293-4597-9d10-f3403eb9df43.png)

**Comment by langkhach270389** [comment]
![7626EBA2-B3E6-4202-A944-478DE97F0AD2](https://user-images.githubusercontent.com/13623692/130551542-f90bb204-0834-4b02-aa59-cb23fc67f8d3.png)
