### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by dionassydqi** [deividgdt/ytadsblocker#2]
./ytadsblocker.sh: line 139: echo: write error: No space left on device

I tried to install it, but why is there a statement that there is no memery available, even though there are still 5GB more free space on my device.

**Comment by deividgdt** [comment]
Hi there,

Please double check if you have space left on the device on /var/log or /var. I think that there is not other possibility to be receiving this error, the line 139 is just an echo with some information that is being forwarding to: /var/log/ytadsblocker.log

`YTADSBLOCKER_LOG="/var/log/ytadsblocker.log"`
`echo "[$(date "+%F %T")] Searching Googlevideo's subdomains in the logs..." >> $YTADSBLOCKER_LOG `

Kind regards,

**Comment by dionassydqi** [comment]
yes, I am also surprised, because there is still 4gb of free memory. For how it works, does it read the query logs related to googlevideo.com and then insert it digravity?

**Comment by deividgdt** [comment]
Hi,

That's exactly how it works. 

Regarding this issue, can you write some on: /var/log ? Did you try it?

Kind regards,

**Comment by dionassydqi** [comment]
I can't find the logs, instead of having to unload the gravity database, why not just read from the query log?

**Comment by deividgdt** [comment]
Did you solve it?
