### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by ajavibp** [deividgdt/ytadsblocker#22]
Sorry if I misunderstood, but if you're trying to filter all the subdomains that match a regular expression, isn't it easier to add that regular expression as a filter directly in Pi-Hole (Domains/RegEx filter)?

Pi-Hole Documentation: https://docs.pi-hole.net/regex/overview/

**Comment by albertvaka** [comment]
+1, I don't understand what this does otherwise.

**Comment by deividgdt** [comment]
Hi, 

As I have discussed it in other forums, if you do that, YouTube will stop working completely. 

You can try it. 

Using the script, will reduce the ads in some way, but you will continue watching them, anyway.  Currently, blocking all the ads using DNS is quite tricky.
