### ISSUE TITLE
Video loading issues

### ISSUE THREAD

**Issue by Keith-Savage** [deividgdt/ytadsblocker#3]
I'm having some issues loading videos on both my television and desktop. I'm a little new to all this, how do I remove the Git clone please?

Thank you

**Comment by deividgdt** [comment]
Hi,

You can disable the script just executing:

`systemctl disable --now ytadsblocker`

Or you can remove it:

`ytadsblocker.sh uninstall`

Also, you can disable the group 'YTADSBLOCKER' on the Pihole configuration at 'Group management' -> 'Groups'.

Kind regards,

**Comment by Keith-Savage** [comment]
Excellent, thanks very much. I may have another go when I'm a little more advanced :)
