### ISSUE TITLE
Reenviar Html modificado de la página

### ISSUE THREAD

**Issue by aggarcia42** [deividgdt/ytadsblocker#4]
Desde hace un tiempo he investigado pihole, es posible realizar un sistema de limpieza publicitario completo mediante DNS? es decir la raspberry abre la página la limpia con Ublock y reenvia el html al dispositivo?

**Comment by deividgdt** [comment]
Buenas Aggarcia42,

Mediante DNS no, pero se podría conseguir algo mediante algún proxy; navegas a través del proxy y digamos que él se encarga de realizar ese proceso de limpieza, el problema es que algunas web hoy día usan diversos métodos para detectar si la publicidad se esta mostrando o no.  Sería una buena labor de investigación.

Un saludo,
