### ISSUE TITLE
Running with dockerized version of pi hole instruccions

### ISSUE THREAD

**Issue by DanielRamosAcosta** [deividgdt/ytadsblocker#5]
I'm using [pi hole dockerized version](https://hub.docker.com/r/pihole/pihole) as I have several docker containers in my Raspberry. How do I run this script? from outside the container? should I enter the container and execute the script?

I've tried reading the source code but still, I cannot guess what to do.

Thanks!

**Comment by deividgdt** [comment]
Hi Daniel,

You can run this script in the Pihole container by executing the script as follow:

```
docker exec -it your_pihole_container bash
wget https://raw.githubusercontent.com/deividgdt/ytadsblocker/master/ytadsblocker.sh
chmod u+x ytdadsblocker.sh
./ytadsblocker.sh install

```
Once the script is installed you can run:
`./ytadsblocke.sh start &`

Also, you can take a look to my blog, where someone had some errors installing the script in a container Pihole, maybe it could help you:

[Youtube Ads blocker 3.0 for Pihole 5.0](https://deividsdocs.wordpress.com/2020/05/30/youtube-ads-blocker-3-0-for-pihole-5-0)

Kind regards,

**Comment by DanielRamosAcosta** [comment]
Thanks @deividgdt !
