### ISSUE TITLE
When I assign YTADSBLOCKER to a client I always get infinite loading on youtube, no video loads. 

### ISSUE THREAD

**Issue by OliverWasson** [deividgdt/ytadsblocker#6]
Worked well for a couple hours, now I cannot use this method :( I like this script you have made though! How would I get this to work?

**Comment by deividgdt** [comment]
Hi Raul,

As i said in some post in my blog some moths ago, these subdomains are generated randomly based on where you're connecting to Youtube. So these links will work for you, but not for me.

Kind regards,
