### ISSUE TITLE
Script not founding googlevideo domains

### ISSUE THREAD

**Issue by amibumping** [deividgdt/ytadsblocker#7]
Hi, I installed yesterday the script, but it says that it hasn't found domains, but there are a few in pihole query list as you can see..

![Screenshot_2021-03-02 Pi-hole - DietPi](https://user-images.githubusercontent.com/25581352/109625638-d9abc080-7b3f-11eb-980f-42cb4463be59.png)

The service is running, but no change.

Thank you.

**Comment by amibumping** [comment]
Sorry it was, because it wasn't activate it the query logging, I didn't know pihole had 2 files where it saves the logs.

**Comment by ftonioli** [comment]
Hello,

I have the same issue now.

If I uninstall, then install, scripts is able to read log file and add domains.

After start, no more domains are added, even they are showed on QueryLog.

I did some tests but could not figure out whats is going on.

Can you help-me ?

**Comment by ftonioli** [comment]
Hello,

I have the same issue now.

If I uninstall, then install, scripts is able to read log file and add domains.

After start, no more domains are added, even they are showed on QueryLog.

I did some tests but could not figure out whats is going on.

Can you help-me ?
